apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery
spec:
  replicas: 2  # Corresponds to instances in TAS
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: your-docker-image
        command: ["celery"]
        args: ["-A", "task_producer.tasks", "worker", "--loglevel=info", "-n", "worker1", "--concurrency=4"]
        env:
        - name: hcp_id
          value: ""
        - name: hcp_data
          value: ""
        resources:
          limits:
            memory: "1Gi"